- __tests__/services/MapConfigTransformService.test.js
- js/services/MapConfigTransformService.js
Adds the ability to use a proxy for the map config sources.
It can be useful especially for testing to use a proxy instead of the direct source url.
A lot of geonode servers don't support CORS and can't be integrated and displayed without a proxy in between.
This change helps in adding support for a proxy. if no proxy is passed in, nothing changes.
> Proxy for MapConfigs

- __tests__/services/WMSService.test.js
- js/services/WMSService.js
As @milafrerichs pointed out, currently the urls are not correct as we pass the proxied url to openlayers and openlayers appends the request. Instead we need to intercept the request from openlayers and proxy it only when the url is ready
> Properly handle requesting images with a proxy now

- package.json
Added Parallelshell to support a double watch. 
Added the ability to watch css and JS and move them to the release/
setup: npm i
run: npm run watch:all
also added npm watch:css just to watch for CSS changes
> added a file watcher and parallelshell to support watching .js and .css

- __tests__/components/Rotate.test.js
- __tests__/components/Zoom.test.js
- js/components/Rotate.js
- js/components/Zoom.js
There was still some code using the old deprecated animations, and since we did not have any unit tests, I didn't catch this.
Added unit tests and updated the code.
SDK-328
> Change all animation code

- package.json
Adding back in node-sass, was dropped form a bad merge
> Adding back in node-sass build

- src/components/QGISPrint.js
this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/195
it was hard-coded to landscape
> Print orientation should not always be landscape

- __tests__/stores/LayerStore.test.js
- src/stores/LayerStore.js
this came up in my testing of https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/224
It seems not possible for QGIS to get the featureNS see: https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/245#issuecomment-286786623
> Handle WFS layers without featureNS from QGIS WAB

- src/components/Bookmarks.js
this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/254
@wnordmann looks like the css gets applied in menu mode as well, which can't be your intention in the rewrite probably, so I changed the css class
I also changed the button implementation to get rid of a warning about iconStyle on div
> Fix bookmark component in menu mode

- __tests__/components/Fullscreen.test.js
- src/components/Fullscreen.js
- src/full.js
SDK-360
the zoom buttons etc. are not visible in the fullscreen mode, since they are not in the map's viewport, not sure if this is an issue though. You can use keyboard and mouse for map navigation in fullscreen mode.
Also, I did not implement an exit button, since the browser already notifies that Esc exits fullscreen mode.
> First implementation of full-screen component

- src/components/LeftNav.js
Otherwise the feature table will not show up correctly
> Make sure leftNav has the correct height

- __tests__/stores/LayerStore.test.js
- src/stores/LayerStore.js
Fixes SDK-414
Only trigger a single change event in the case of move layer
> Fix issues with StyleModal after drag drop

- src/components/Login.js
- src/components/MapConfig.js
So the flexible ellipsis option described in SDK-419 had all kinds of issues (interactions deactivated too early, modals dismissed too early), so I decided to go with an alternative path, i.e. change Login to use IconButtons and change MapConfig to use a different icon other than the ellipsis icon that suggests that we can put other things in there. We can revisit an ellipsis option later after 1.0 release, but this seems the only viable option for now.
> Change Login and MapConfig to use icons

- src/components/LayerList.js
- src/components/Select.js
This brings back toggle mode for layer list with a bit of css at the app level as can be seen here: https://github.com/boundlessgeo/sdk-apps/commit/ac9e312290b7afce9cd30a07ddc330d56235c8c2
@volaya we probably need to make a similar change as the one above in WAB
> Bring back toggle mode for layer list

- src/components/LayerList.js
This brings back the add layer option to toggle mode of LayerList
> Bring back add layer option to toggle mode

- src/components/LayerListItem.js
This is happening in some cases with the code generated by WAB
> Protect against tablemodal ref not being initialised

- src/components/LayerListItem.js
this came up in: https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/337
for the table modal the edit tools make no sense
> Do not allow edit tools in table modal

- package.json
- src/actions/MapActions.js
- src/components/Map.js
- src/components/MapView.js
- src/reducers/map.js
simplifying what is stored in state tree until more actions are created. trying to prevent erroneous, out-of-date map data from being stored in state tree
> only saving relevant zoom info in state tree

- examples/basic/app.js
- package.json
- src/components/map.js
1. Map component now adds vector layers to the map
appropriately.
2. Package.json now includes the MapBox-to-OL style dependency
for translating GL styles to OL styles.
3. Basic demo now has an "add random point" button to demonstrate
the addFeatures action working dynamically.
> Added support for geojson source + vector layers

- __tests__/components/map.test.js
- src/components/map.js
Currently, hide OSM is broken in the basic example.
This fixes it, and creates a unit test for it.
> Fix layer visibility updates

- __tests__/components/map.test.js
- src/components/map.js
- src/reducers/map.js
This fixes an issue in the basic example where the states layer cannot be added a second time after removal.
> Layer could not be re-added

- .travis.yml
- DEVELOPING.md
- __tests__/actions/drawing.test.js
- __tests__/components/map-drawing.test.jsx
- __tests__/components/map.test.jsx
- __tests__/reducers/drawing.test.js
- examples/drawing/app.css
- examples/drawing/app.jsx
- examples/drawing/index.html
- examples/index.html
- package.json
- src/action-types.js
- src/actions/drawing.js
- src/components/map.jsx
- src/constants.js
- src/reducers/drawing.js
- webpack-dev-server.config.js
1. Added a special reducer/action set in order to handle
the drawing functions (as they are not covered by mapbox gl styles).
2. Modified the map component to use drawing.interaction and drawing.sourceName
props for identifying when a feature is being drawn and on to what.
3. Created an example app with a working demo that includes onFeatureDrawn
which is the call back provided upon a features drawing completion.
4. Needed to add the canvas module to the dev dependencies.
By default jsdom/enzyme/jest does not emulate the canvas, they
depend on the canvas package. This may not be practical to install
for all dev environments (looking at you, Windows) and may need to
be shifted to a peerDependency.
5. The map has withRef: true in order to support introspection.
Refs: SDK-500, SDK-535
> Features can now be drawn on the map!

- __tests__/actions/map.test.js
- __tests__/components/history.test.jsx
- __tests__/root/util.test.js
- examples/basic/app.jsx
- src/actions/map.js
- src/components/history.js
- src/util.js
The "built-in" component only handles location
but is structured in such a way that it could
be extended to track more items.
To support this query-string handling functions have
been added to util.
The parseQueryString and encodeQueryObject are used
to convert URL encoded query strings to objects and vice-versa.
Refs: SDK-573
> Added hash-based history tracking.

- examples/basic/app.jsx
Setting the map name was broken in the basic example, this PR fixes it
> Fix setting the map name

- __tests__/components/history.test.jsx
- __tests__/components/map.test.jsx
- examples/basic/app.jsx
- examples/clustering/app.jsx
- examples/drawing/app.jsx
- examples/paint-change/app.jsx
- examples/popups/app.jsx
- examples/wms/app.jsx
- src/components/history.js
- src/components/map.jsx
1. Updated the map component to normalize the center
from 4326 and to set the center as 4326 when moveend
is triggered.
2. Made a small tweak to the history component to prevent
insignificant digits from floodings the hash-url.
3. Updated tests to conform to the new 4326 rule.
4. Updated the example applications to also use 4326 to
set the view.
REFS: SDK-624
> Fixed setView projections bug.

- examples/basic-wgs84/app.css
- examples/basic-wgs84/app.jsx
- examples/basic-wgs84/index.html
- examples/index.html
- src/components/map.jsx
- webpack-dev-server.config.js
Demonstrates:
1. Setting the map-projection to EPSG:4326
2. Putting a EPSG:4326-native set of background imagery on the map.
Fixes included:
Puts the appropriate reprojection code where required. There's 
Refs: SDK-607
> Added EPSG:4326 example.

- .travis.yml
- README.md
- package.json
Installing the canvas module has system requirements that
are not universally necessary for INSTALLING SDK.  They are
really only useful for running the test suite.
The tests which use canvas have checks to see if it is installed
making it, essentially, an optional install.
> Drop Canvas from devDeps

- examples/upload-map/app.js
- examples/upload-map/context-selector.js
- examples/upload-map/index.html
save button saves map spec to .json file - i added it to this app so you can demo saving a spec file, altering it, and re-uploading it into the app.
JIRA SDK 554 - the jira ticket mentions wmc format but this button saves the file as .json, per talks w/ Walker and the team. 
Right now the whole map state is saved but if less or more info is needed for the map state - ie, state.map.sprite? - let me know.
> Adding export map action to Upload App

- config/examples/example.html
- package.json
- src/stylesheet/sdk.scss
- tasks/create-package-json.js
- webpack-dev-server.config.js
1. Made sdk path relative.
2. Created new "bundle-examples" script which:
a. Builds the Examples HTML
b. Builds a static CSS file for the examples
c. Outputs the individual bundles per example.
This allows the examples to be served from a static directory
or non-Webpack-based server.
3. npm run dist will now output a babelified version
of SDK with the SASS stylesheet and a more appropriate package.json.
I've tested this using `yarn add file:...` with the rest of the quickstart
instructions.
> Updates to ready NPM Publishing

- webpack-dev-server.config.js
The ol CSS inclusion was using a ".css" import which was
not inlining the ol CSS. Yesterday, that was changed to properly inline
the OL CSS when doing `npm run build:css` but the webpack configuration
was missing the necessary new includePaths.
> Correction for Sass Loader to include node_modules

- __tests__/components/map-time.test.js
- src/components/map.js
If the map time was set before adding the source, the TIME parameter would not getting set.
> Add initial TIME parameter for WMS sources

- __tests__/components/map-time.test.js
- src/components/map.js
- src/constants.js
SDK-650
Since it was necessary for replicating this example: https://www.mapbox.com/mapbox-gl-js/example/timeline-animation/ this PR also introduced a prop on the map component to configure wrapX
> Allow time filtering of vector layers

- __tests__/actions/map.test.js
- __tests__/components/map-geojson-source.test.js
- src/actions/map.js
- src/reducers/map.js
Adding test to make sure mixed case works
This could be changed to error once error handling is implemented, without this `type:geoJson` would work fine inside SDK/Redux but does nothing in Open Layer creating a confusing situation.
> Adding a toLower to protect source typos ie - geoJson

- config/examples/example.html
- package.json
- webpack-dev-server.config.js
- webpack-example.config.js
Per the discussion in slack, I'm moving sdk.css into the examples directory
> Move sdk.css into examples directory

- src/components/map.js
- src/components/wfs.js
This PR fixes 2 issues:
- DOM manipulation that seems unnecessary will break React 16, so let's fix it now already
- React 16 warns about PureComponent that uses shouldComponentUpdate
> Miscellaneous fixes

- __tests__/components/map-geojson-source.test.js
I added this test at the last minute to quell a curiosity I had,
the test passed but was technically incorrect.  This fixes that
bug.
> missed a typo/false test during geojson merge.

- package.json
this is used by ```tasks/dist-copy``` and ```tasks/create-package-json```
as reported by @wnordmann
> Add fs-extra as a dev dependency

- src/components/map.js
This more forcefully updates the loader using `loader_ =` instead of `set('loader',..` which didn't appear to actually work.
> Fix for the loader not updating properly with GeoJson layers

- DEVELOPING.md
- README.md
SDK needs to have the package "built" to properly work with
a project. This documents the steps to creating the package
and then linking to it for local use.
> Wrote "npm link" how-to

- examples/feature-table/app.js
- examples/feature-table/index.html
Uses the font-awesome icons to represent the
airports as little airplanes on the map.
It's both cute AND demonstrates using a font as an icon
alternative to a "circle" type layer.
> Added fontawesome/font-icon example

- src/components/map.js
- src/components/map/popup.js
Since #662 popup autoPan was broken. This PR adds a different solution than the DOM manipulation we did back then.
I'm not 100% happy with having to pass a reference to the map to the popup, but I couldn't think of a better approach.
@CarlyLanglois would be great if you can confirm that this fixes things for you.
@theduckylittle would like to have your feedback on this one
> Fix for popup autoPan

- src/components/map.js
the children proptype can be a node or an array of nodes
> Use correct propType for children in Map

- DEVELOPING.md
- docs/getting-started.md
create-react-app will not be able to _build_ a bundle due to some issues with various SDK dependencies. These instructions provide detail on what to do next.
> Instructions on Ejecting Create-React-App

- tasks/dist-copy.js
Our dist-copy task was showing a deprecation message, this PR fixes this:
```
(node:5531) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Created package.json in /home/bartvde/opengeo/git/sdk_bartvde/dist/package.json
```
> Prevent deprecation message in dist-copy task

- __tests__/components/__snapshots__/legend.test.js.snap
- src/components/legend.js
SDK-738
This PR fixes multiple issues with vector legends:
- legends will get overwritten
- legends did not use strokes
- legends from multiple layers were being the same as the last layer
> Vector legend fixes

- webpack-dev-server.config.js
This came up in SDK-666
It's to fix https://reactjs.org/docs/cross-origin-errors.html
> Use different devtool to prevent CORS warning

- changelog/upgrade-notes.md
This is a follow-up from #721 forgot to add a note to the upgrade notes that the import for layer list item has changed
> Add note to upgrade notes for changed import

- src/components/map.js
- src/constants.js
Before the queryable boolean metadata needed to by typed out manually each time.
> Made "bnd:queryable" a constant.

- src/components/map.js
1. Added the ability to use vector tiles in identify.
Vector tile layers will not return a fully hydrated feature,
now the identify function picks up on that.
2. Also added BBOX style URL substitutions that allow using WMS
to return a protobuf "image".
> WMS and Identify support for vector tiles.

- package.json
- src/actions/map.js
1. Small change to package.json to include the jest-cli.
I believe in older version of Jest this is included but I was
getting an error that tests could not be run without expressly
including the cli package.
2. New actions which short-hand the creation of complex source
definitions.
> Add additional helpers for configuring sources

- examples/paint-change/app.js
The stroke of the circle in paint-change example was never visible, this is because the default value of circle-stroke-width is 0
Before this was not enforced in mapbox-to-ol-style so we did not notice it
> Make sure we set circle-stroke-width

- __tests__/reducers/map.test.js
- examples/basic-wgs84/app.js
- examples/basic/app.js
- examples/bookmark/app.js
- examples/clustering/app.js
- examples/drawing/app.js
- examples/export-image/app.js
- examples/export-image/wms.json
- examples/feature-table/app.js
- examples/filter/app.js
- examples/geolocation/app.js
- examples/layer-list/app.js
- examples/legends/app.js
- examples/paint-change/app.js
- examples/popups/app.js
- examples/realtime/app.js
- examples/rotating/app.js
- examples/sprite-animation/app.js
- examples/sprites/app.js
- examples/wfst/app.js
- examples/wms/app.js
- src/reducers/map.js
- layers need to have a type or ref (SDK-722)
- filter cannot be null (SDK-774)
Also fixes SDK-776 (overlay not visible in export image example)
> Fixes to be more in line with Mapbox GL JS / style spec

- __tests__/root/util.test.js
- src/components/layer-list-item.js
- src/util.js
1. Needed to expose the isOver and DragPrevew API's of
react-dnd to improve catalog interactions.
2. Added a getLayersByGroup function which is useful for
collecting a set of style layers to be saved in GeoServer.
> Added getLayersByGroup func, exposed more dnd API.

- examples/basic-wgs84/app.js
- examples/basic/app.js
- examples/feature-table/app.js
- examples/filter/app.js
- examples/geolocation/app.js
- examples/layer-list/app.js
- examples/paint-change/app.js
- examples/rotating/app.js
- examples/wfst/app.js
- examples/wms/app.js
SDK-773
In our examples we were sometimes using a background layer on top of an OSM layer. This doesn't make sense. I've removed the background layer from examples where it doesn't make sense (e.g. OSM layer for which visiblity cannot be changed), and I've added it to the layer list example, at the bottom of the layer stack, where OSM can actually be toggled so we get to see the background.
> Only use background layer in examples for which it makes sense

- examples/filter/filter.js
Since the filter is not initially null anymore after #746 we needed to update the filter example
> Do not check for null filter but falsey instead

- __tests__/reducers/map.test.js
- src/components/map.js
- src/reducers/map.js
This came up during SDK-780, it made the code easier and more efficient to find differences if we set the metadata for layers and sources version when we receive a new context.
> When receiving context, set layer and source version metadata

- package.json
react-dnd / disposable was causing babelrc issues.
> Move DND to a peer to fix compile time errors.

- __tests__/components/map-geojson-source.test.js
- __tests__/components/map.test.js
- __tests__/components/map/__snapshots__/zoomslider.test.js.snap
- __tests__/reducers/map.test.js
- src/components/map.js
- src/constants.js
- src/reducers/map.js
SDK-786
Mapbox GL JS (and the style spec) is based on 512 pixel tiles, so we need to adjust the openlayers zoom level
> Make sure zoom levels are equal

- package.json
https://sdk.boundlessgeo.com/basic/index.html is currently broken (all examples are) because of a bug in ol 4.6.0 that was used when the last build kicked off. This has been fixed in ol 4.6.2.
This kicks off a new build.
```
Uncaught Error: Cannot find module "../../layer/vectorrendertype.js"
```
> Move to ol 4.6.2 to fix sdk.boundlessgeo.com

- src/components/layer-list.js
When creating groups, pass through additional props if configured.
Refs: SDK-799
> Allow the layerlist to pass props to a group class

- examples/feature-table/app.js
- examples/wfst/app.js
This is a small fix to one of our examples. The example HTML template already handles the inclusion of app.css if it's present. https://github.com/boundlessgeo/sdk/blob/master/tasks/build-examples.js#L61:L66
> No need to import app.css, this is handled by template

- webpack-dev-server.config.js
- webpack-example.config.js
Currently the examples are down because of this
> Protect against not having .env file

- src/stylesheet/_scaleline.scss
In castling, the scaleline control is not in the controls div, so make sure our css selector is not so fussy
> Scaleline might not always be in controls div

- __tests__/components/__snapshots__/legend.test.js.snap
- __tests__/components/legend.test.js
- src/components/legend.js
This came up with creating a legend for the castling app, some legends would not show up. This is because the sprite has not yet been loaded. If applyStyle finishes loading of the sprite image it will call changed on the vector layer, so we can use that hook.
> If legend depends on sprite, we need to wait for it to load

- __tests__/components/map.test.js
- src/components/map.js
This gives apps the opportunity to update the map div's dimensions and get it reflected properly without a skewed map
> Call updateSize on map if size changes

- __tests__/components/map/__snapshots__/scaleline.test.js.snap
- __tests__/components/map/scaleline.test.js
- src/components/layer-list.js
- src/components/map/scaleline.js
This was a small oversight in #774 which did not allow for setting a custom className on the root div, which is actually needed for castling where we need two scalelines
cc @theduckylittle
> Allow setting className on ScaleLine

- __tests__/components/map-time.test.js
- changelog/upgrade-notes.md
- src/components/map.js
- src/constants.js
When we initially designed the time based support, we had a single metadata attribute key for time based datasets. However is it common to have a start and an end attribute, where the second one is optional. This is also how it works in Exchange. So  this PR changes that behaviour. The actual filtering will still take place at the application level.
> Replace single time attribute with start and end

- __tests__/components/mapboxgl.test.js
- package.json
- src/components/mapboxgl.js
Updates the support for mapbox draw. It was not working properly. 
multiple instances of Draw do not share any information and would
destroy all features and elements. rather than creating a new instance
we simply change the mode of them.
the static mode which does not allow anything is the default mode
> Change mapbox gl draw to use a single instance

- src/components/mapboxgl.js
the mode `direct_select` needs a `featureId` to work properly. 
but the featureId is the internal mapboxdraw feature id.
so I added an options parameter to inDrawModify to accept additional options to be passed to `changeMode`
> Fix modifying a feature broke the selection

- __tests__/components/mapboxgl.test.js
- __tests__/reducers/drawing.test.js
- examples/drawing/app.js
- src/actions/drawing.js
- src/components/mapboxgl.js
- src/reducers/drawing.js
It adds the ability to change the modes for every interaction. 
And change the mode that will be used after the interaction is finished. 
it is possible with mapbox draw to have custom modes, this PR adds the
ability to assign them to the map and change them with the call to the
interactions.
there will be a mode for the interaction itself and one to switch to
after the interaction is done.
for example you want to draw new features, but after the feature is done
you don't want toi create another feature but rather change the newly
created one.
_Checks if the listener was added before and does not add them again_
this caused a bug in our system, that changing the mode often would cause the callback to be called multiple times. 
prevent that by checking if the listener was already added. it …
> Add ability to set modes for drawing

- __tests__/components/mapboxgl.test.js
- src/actions/drawing.js
- src/components/mapboxgl.js
It adds the ability to pass options to changing the mode to mapbox draw.
More info about custom modes:
https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/MODES.md
we have a use-case where we have a custom mode, which needs more options
passed to it. mapbox draw allows to create custom modes and add options
on initialization (changeMode) to it.
it does not affect any other drawing features
> Add currentModeOptions to allow passing options to the mode

- __tests__/actions/map.test.js
- __tests__/components/map-cluster.test.js
- __tests__/components/map-context.test.js
- __tests__/components/map-geojson-source.test.js
- __tests__/components/map-sprite-animate.test.js
- __tests__/components/map-time.test.js
- __tests__/components/map.test.js
- src/actions/map.js
- src/components/map.js
SDK-862
This came up when porting https://github.com/boundlessgeo/ol-mapbox-style/pull/39 to SDK.
So ```type: 'vector'``` comes in two forms:
1. url, this is the url to a TileJSON resource, which is then fetched and parsed, and only then can we construct the actual source
2. tiles, a set of tiles, this is the way we were using url before
So we were incorrectly using url before, where we should have been using tiles. And when using url, it will need async / promise based creation of sources. This had quite a bit of influence on the unit tests, where some of them now need to run in a setTimeout callback.
> Async creation of sources

- src/components/map.js
This fixes the latest 3 issues reported by SonarQube
We should find a way to detect them earlier.
> Do not define functions in loop

- src/components/mapboxgl.js
Under certain circumstances `shouldComponentUpdate` can apparently get called before any sources have been added to the map. This then results in a TypeError:
```
TypeError: Cannot read property 'setData' of undefined
MapboxGL.shouldComponentUpdate
./node_modules/@boundlessgeo/sdk/components/mapboxgl.js:197
194 | if (src && src.type === 'geojson') {
195 |   var version_key = (0, _map2.dataVersionKey)(src_name);
196 |   if (this.props.map.metadata !== undefined && this.props.map.metadata[version_key] !== nextProps.map.metadata[version_key] && this.map) {
> 197 |     this.map.getSource(src_name).setData(nextProps.map.sources[src_name].data);
198 |     if (this.draw) {
199 |       if (nextProps.map.sources[src_name].type === 'geojson') {
200 | …
```
> Quick fix to check for the existance of sources before trying to call setData

- __tests__/components/mapboxgl.test.js
- src/components/mapboxgl.js
Moved side effects from `shouldComponentUpdate` to `componentWillReceiveProps` since side effects in `shouldComponentUpdate` should be avoided.
> moving side effects to componentWillReceiveProps

- __tests__/components/mapboxgl.test.js
- changelog/upgrade-notes.md
- examples/drawing/app.js
- src/components/mapboxgl.js
SDK-880
1. no box zoom anymore in mapbox gl map
2. onFeatureXXX callbacks need to pass a collection now
3. sourceName in callback functions should be correct
4. lines are not visible when drawing with the openlayers map in the draw example
So the draw control disabled the box zoom, see: https://github.com/mapbox/mapbox-gl-draw/blob/master/src/setup.js#L36
So we should only create the draw control when we actually need it.
In addition in #804 we had changed the interface of the onFeatureXXX callback functions to pass a collection instead of a single feature, but this had not yet been changed in the mapbox gl map component, so the drawing example was broken for the mapbox renderer, this PR also addresses this
> Fix several issues with the drawing tools

- src/components/map.js
Tests for null and undefined in the current and next states.
I found some situations where unloading and loading the map could cause odd states in the mapinfo reducer's size.
> More thorough test for size changes.

- __tests__/components/mapboxgl.test.js
- src/components/mapboxgl.js
When the source is updated we need to remove the old features from the
draw instance, otherwise there will be artifacts in mapbox draw with a
layername `.cold` or similar. ensure we delete all the features from
draw before adding them again. this avoids adding features multiple
times as well
will add delete feature to the demo shortly after this PR.
fixed a bug as well for the draeing demo.
You got an error when you changed the layer but did not select a different mode resulting in `this.draw` to be undefined.
> Remove artifacts from map

- src/components/map.js
When a source is created and needs an immediate update, an error
was being thrown as the source-creation is now done asynchronously.
Adding a promise to wrap the update of sources ensures the source
has been created before trying to update it.
> Fix for async source/update cycle.

- __tests__/components/map.test.js
- src/components/map.js
This is a follow-up to #818 to do the same for the OpenLayers based map component
> Move side effects outside of shouldComponentUpdate

- package.json
- src/components/ArcGISRestLegend.js
Fixes ArcGIS rest endpoints to also use proxy if one is defined
> Proxy ArcGIS REST for legends

- __tests__/services/ArcGISRestService.test.js
- src/components/ArcGISRestLegend.js
- src/services/ArcGISRestService.js
Need to defer getLegendUrl to using source which has knowledge of proxy. Updating test to reflect change
NOTE: Test needs to be updated to use source in the same manner as the function has been changed.
This change has been done to properly proxy the legend graphic, as the previous implementation was unsuccessful. The proxying needs to be done after the url manipulation within the ArcGISRestService.
> Fix proxying of ArcGISRestLegend.

- __tests__/reducers/map.test.js
- src/reducers/map.js
This came up in SDK-951 where the order of the layer stack in the preview map was incorrect. This is because we were passing positionId to the measure layer in the action, but the measure layer is not in the preview map stack. This PR handles this case more gracefully, as if no positionId was passed at all in case it's not found. Also adds tests which were missing altogether for positionId.
> Handle correctly if positionId not found

- __tests__/components/map.test.js
- src/components/map.js
If set to false, the map will not have any interactions in it, and hence will not response to any mouse or keyboard events
> Add a prop to make a map not interactive

- package.json
- src/services/MapConfigTransformService.js
Uses the layer.layerid to `show` only this ArcREST layer
https://developers.arcgis.com/rest/services-reference/export-map.htm - see `layers`, `show` param
> Use show in layers parameter value for ArcGIS REST

- src/components/map.js
ol-mapbox-style applyStyle returns a promise that can get rejected if the sprite cannot be loaded, and we were not handling this
> Handle promise rejection from ol-mapbox-style applyStyle

- __tests__/components/map.test.js
- src/components/map.js
This is taken from #861 since it might take a while before we upgrade, and it fixes actual issues in the current code base
> Fix undefined refs which kills Mapbox libs, have default zoom and center

- .eslintrc
- __tests__/components/mapboxgl.test.js
- __tests__/components/wfs.test.js
- src/components/map.js
This is to fix:
```
Uncaught TypeError: setSourceError is not a function
at _ol_source_TileWMS_.<anonymous> (map.js:977)
at _ol_source_TileWMS_.boundListener (events.js:16)
at _ol_source_TileWMS_../node_modules/ol/events/eventtarget.js._ol_events_EventTarget_.dispatchEvent (eventtarget.js:86)
at _ol_source_TileWMS_../node_modules/ol/source/urltile.js._ol_source_UrlTile_.handleTileChange (urltile.js:132)
at _ol_ImageTile_.boundListener (events.js:16)
at _ol_ImageTile_../node_modules/ol/events/eventtarget.js._ol_events_EventTarget_.dispatchEvent (eventtarget.js:86)
at _ol_ImageTile_../node_modules/ol/tile.js._ol_Tile_.changed (tile.js:73)
at _ol_ImageTile_../node_modules/ol/imagetile.js._ol_ImageTile_.handleImageError_ (imagetile.js:106)
at Image.boundListener (events.js:16)
```
> Do not redefine setSourceError from import

- src/components/map.js
So it doesn't fail when used from the not connected component class
> Add default prop for setSourceError

- src/components/wfs.js
Refs MBSE-79
This allows for sending a WFS-T update without the geometry, if the geometry has not changed
> Handle empty geometries in WFS Update

- src/components/map.js
This came up in MBSE-168
See the OpenLayers API docs for getArea:
```
* Get the spherical area of a geometry.  This is the area (in meters) assuming
* that polygon edges are segments of great circles on a sphere.
* @param {module:ol/geom/Geometry} geometry A geometry.
* @param {module:ol/sphere~SphereMetricOptions=} opt_options Options for the area
*     calculation.  By default, geometries are assumed to be in 'EPSG:3857'.
*     You can change this by providing a `projection` option.
* @return {number} The spherical area (in square meters).
*/
```
We were doing the transform ourselves, and not passing in the projection.
> We should not feed geometry in EPSG:4326 to getArea

- __tests__/components/map-geojson-source.test.js
- changelog/v2.6.2.md
- package.json
- src/components/map.js
- src/constants.js
```
map: {
metadata: {
'bnd-sources-fetch-options': {
'foo': {
headers: {
'Authorization': 'foo'
}
}
}
},
sources: {
'foo': {
type: raster',
..
},
},
```
> Allow setting fetch options at the source level

- __tests__/components/map-drawing.test.js
- changelog/v2.6.3.md
- package.json
- src/components/map.js
this came up in SDK-1062
If you select feature A, the events will be okay.
If you then select feature B, the selected callback will happen, but the deselected callback for feature A will not happen.
This PR fixes it and adds a test.
> There can be both selected and deselected features in the ol event

- changelog/v2.6.4.md
- package.json
- src/components/map.js
When drawing the event can come from multiple interactions. In some cases it might make sense being able to distinguish between a box and a normal polygon. In such cases it makes sense to pass the interaction in the callback.
> Pass the interaction for draw events

- src/components/legend.js
- src/constants.js
- If a layer's metadata includes legend-type and legend-content, skip the code to try to dynamically create a legend, and use what has been defined in the metadata.
- Adds `LEGEND_TYPE` and `LEGEND_CONTENT` to constants
> Allow legend to be specified in layer metadata

- src/components/map.js
When checking for queryable layers, first ensure there is
a metadata object.
> Check for missing metadata in layer

- __tests__/components/mapboxgl.test.js
- package.json
- src/components/map.js
- src/components/mapboxgl.js
Instead of passing the map-object along both Mapbox GL maps
and OpenLayers maps will create an object containing
the relevant data and then pass that to setView.
> Review setView to not send the map object

- __tests__/components/layer-list.test.js
- examples/layer-list/app.js
- examples/wms/app.js
- src/components/layer-list.js
According to the react-dnd docs the context should
be set for the entire application.  While developing an app
I found that I could not add other DND targets or sources because the
context was limited to only the layers list.
> Bug: Do not set HTML context on the component.

- __tests__/components/map.test.js
- src/components/legend.js
- src/components/map.js
- webpack-common.js
```ol-mapbox-style``` 3.3.0 will throw an error if the source cannot be found in the sources definition, so we need to amend our fake styles with sources
> Make sure we pass in sources in our fake style

- changelog/v2.7.4.md
- docs/getting-started.md
- package.json
With react-redux version 6, our getting started guide broke
Also ejecting is not needed anymore with the latest create-react-app, so that section was removed.
I also moved advanced stuff to the end of the tutorial to not complicate things for the novice, it's already complicated as it stands
> Fix the getting started guide

- changelog/v2.5.2.md
- changelog/v2.6.0.md
It appeared we did not have release notes for 2.5.2 and we accidentally included a bug fix that was already in 2.5.2 in the 2.6.0 release notes
> Add missing changelog for 2.5.2 release

- tasks/build-examples.js
A error is thrown when running build:example script because calling `new Buffer` is deprecated in node.  `    contents: new Buffer(index) `
```(node:15707) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.```
Moved to new `Buffer.from`
> Fixing a deprecated function used in node script
