boundlessgeo/sdk

__tests__/components/LayerListItem.test.js
js/actions/LayerActions.js
js/components/LayerList.jsx
js/components/LayerListItem.jsx
js/constants/LayerConstants.js
js/stores/LayerStore.js
package.json
scripts/test-transform.js

Drag and drop support for LayerList

---

js/components/LayerList.jsx
js/components/LayerListItem.jsx
js/stores/LayerStore.js

Fix up nested layer group drag and drop

---

js/components/FeatureTable.jsx
js/components/LayerList.jsx
js/components/LayerListItem.jsx

Layer list table

---

js/components/FeatureTable.jsx

Handle failure in table

---

__tests__/services/SLDService.test.js
js/services/SLDService.js

Add unit tests for SLD

---

js/components/StyleModal.jsx

with the same assumptions as before

Restore StyleModal functionality

---

__tests__/components/LayerList.test.js
js/components/LayerList.jsx

Add ability to add children to layerlist. So you could add custom elements to it.
if you want add more buttons for example this simple change allows you to add almost anything to the layerlist
example:
```
<LayerList ... >
<h1>New Headline in Layerlist</h1>
<button>New Button</button>
</LayerList>
```

Custom Elements in LayerList

---

js/components/FeatureTable.jsx
js/components/LayerList.jsx
js/components/LayerListItem.jsx

Add collapse option for table options

---

js/components/FeatureTable.jsx
js/services/WFSService.js
js/stores/FeatureStore.js

Allow for remote sort in table

---

js/components/AddLayerModal.js
js/components/ArcGISRestLegend.js
js/components/Legend.js
js/services/ArcGISRestService.js
js/util.js

Arcgis REST legends

---

__tests__/services/ArcGISRestService.test.js
js/components/ArcGISRestLegend.js
js/components/InfoPopup.js
js/services/ArcGISRestService.js
js/services/WMSService.js
js/services/WMTSService.js

Add GetFeatureInfo for ArcGIS REST

---

js/components/FeatureTable.js
js/stores/FeatureStore.js

Fix slow numberOfFeatures queries messing up table content

---

js/components/LayerListItem.js

Allow embedding ArcGIS Legend in LayerList

---

js/components/EditForm.js
js/components/EditPopup.js
js/services/WFSService.js

Allow EditPopup to work on WMS

---

__tests__/components/BaseMapModal.test.js
js/components/BaseMapModal.js
js/components/BaseMapSelector.js
js/components/LayerList.js

Add Base Map Selector functionality

---

__tests__/services/MapConfigTransformService.test.js
js/services/MapConfigTransformService.js

Add support for XYZ in GXP MapConfig

---

js/components/WMSLegend.js

Only add SLD_BODY to request if present

---

js/components/LayerListItem.js

Initial implementation for collapse / expand of groups

---

js/components/AddLayerModal.js
js/services/WMSService.js

see #227 
this is just for WMS GetCapabilities, if the approach works we'll add it everywhere in the SDK
cc @milafrerichs

Optional proxy for XHR requests that can be passed through context

---

__tests__/root/util.test.js
__tests__/services/RESTService.test.js
__tests__/services/WFSService.test.js
__tests__/services/WMSService.test.js
__tests__/services/WMTSService.test.js
js/components/AddLayerModal.js
js/components/InfoPopup.js
js/components/LayerListItem.js
js/components/Login.js
js/components/StyleModal.js
js/services/ArcGISRestService.js
js/services/AuthService.js
js/services/RESTService.js
js/services/WFSService.js
js/services/WMSService.js
js/services/WMTSService.js
js/util.js

this is a continuation of #314 to address #227 fully
closes #227

Add proxy support

---

__tests__/services/MapConfigTransformService.test.js
js/services/MapConfigService.js
js/services/MapConfigTransformService.js

When creating sources from the MapConfig, we need to use a tileLoadFunction as well to apply the proxy
cc @milafrerichs

Use proxy correctly in MapConfig TileWMS

---

js/components/FeatureTable.js
js/components/RuleEditor.js
js/components/StyleModal.js
js/services/SLDService.js

Stylemodal related fixes

---

js/components/AddLayer.js
js/components/Chart.js
js/components/Edit.js
js/components/EditForm.js
js/components/FeatureTable.js
js/components/FilterHelp.js
js/components/GeocodingResults.js
js/components/Geolocation.js
js/components/Globe.js
js/components/HomeButton.js
js/components/LayerList.js
js/components/Legend.js
js/components/LoginModal.js
js/components/PanelButton.js
js/components/PointSymbolizerEditor.js
js/components/PolygonSymbolizerEditor.js
js/components/QGISLegend.js
js/components/QueryBuilder.js
js/components/Rotate.js
js/components/RuleEditor.js
js/components/WFST.js
js/components/Zoom.js

Clean up muiTheme handling

---

js/components/AddLayer.js
js/components/AddLayerModal.js
js/components/Measure.js
js/components/Select.js
js/components/WFST.js

Use more static properties for ol instances

---

js/components/AddLayerModal.js
js/services/WMSService.js

Use GetMap OnlineResource

---

js/components/AddLayerModal.js

Make TextFields in new server dialog full width

---

__tests__/services/WMTSService.test.js
js/components/AddLayerModal.js
js/services/ArcGISRestService.js
js/services/WMSService.js
js/services/WMTSService.js

Do not proxy images

---

js/components/StyleModal.js

see https://github.com/GeoNode/geonode-client/issues/98

Make style modal errors more prominent

---

js/components/AddLayerModal.js

Add loading indicator in add layer dialog

---

js/components/AddLayerModal.js

Be more smart with urls in add layer dialog

---

__tests__/services/MapConfigTransformService.test.js
js/services/MapConfigTransformService.js

This came up in https://github.com/GeoNode/geonode-client/issues/89

Parse bbox from map config

---

__tests__/services/MapConfigTransformService.test.js
js/components/AddLayerModal.js
js/components/LayerList.js
js/components/StyleModal.js
js/services/MapConfigTransformService.js

This came up in https://github.com/GeoNode/geonode-client/issues/115

Support a different restUrl

---

__tests__/services/MapConfigTransformService.test.js
js/services/MapConfigTransformService.js

this came up in: https://github.com/GeoNode/geonode-client/issues/100

Make sure layer config always has a name

---

js/components/AddLayerModal.js
js/services/MapConfigService.js
js/services/WMSService.js

In case of errors, fallback to proxied images

---

docs/tutorial.md
docs/writing_components.md

Updating some import paths in the tutorial

Tutorial update

---

js/components/FeatureTable.js
js/components/QueryBuilder.js
js/components/Select.js
js/components/WFST.js
js/services/WFSService.js
js/stores/FeatureStore.js

Make sure we proxy FeatureStore.addLayer

---

js/stores/FeatureStore.js

Do not clear source unnecessarily

---

__tests__/components/WFST.test.js
js/components/AddLayerModal.js
js/components/MapPanel.js
js/services/MapConfigService.js
js/stores/LayerStore.js

This removes duplicate code from the codebase as well, and enables adding a layer via url in GeoNode

Handle DescribeFeatureType and get style name in LayerStore

---

__tests__/services/WMSService.test.js
js/services/WMSService.js

this came up in  https://github.com/GeoNode/geonode-client/issues/131

Make sure we preserve any existing query params on GetCapabilities

---

__tests__/components/LoadingPanel.test.js
__tests__/services/MapConfigTransformService.test.js
__tests__/services/RESTService.test.js
js/components/StyleModal.js
js/services/MapConfigTransformService.js
js/services/RESTService.js
js/stores/LayerStore.js

we also need a way to use the access token in the requests

Fix up url handling for RESTService

---

js/components/LoginModal.js

Make login and close configurable in LoginModal

---

js/components/LabelEditor.js
js/components/PointSymbolizerEditor.js
js/components/PolygonSymbolizerEditor.js
js/components/StrokeEditor.js

This came up in https://github.com/GeoNode/geonode-client/issues/97

Better style dialog

---

js/components/AddLayerModal.js
js/components/EditPopup.js
js/components/FeatureTable.js
js/components/InfoPopup.js
js/components/LayerListItem.js
js/components/Login.js
js/components/MapPanel.js
js/components/Select.js
js/components/StyleModal.js
js/components/WFST.js
js/services/AuthService.js
js/services/RESTService.js
js/services/WFSService.js
js/services/WMSService.js
js/stores/FeatureStore.js
js/stores/LayerStore.js
js/util.js

closes #372 
cc @wnordmann as this likely influences your fetch work as well

Add option to pass in request headers

---

js/components/BookmarkDots.js
js/components/Bookmarks.js

Changing the dots to be flex layout and moving the navigation arrows down a little

Fixing the layout on the dots

---

__tests__/services/RESTService.test.js
js/services/RESTService.js

Allow RESTService to work on WFS layers as well

---

__tests__/components/FillEditor.test.js
js/components/ColorPicker.js
js/components/FillEditor.js
js/components/FilterEditor.js
js/components/LabelEditor.js
js/components/LineSymbolizerEditor.js
js/components/PointSymbolizerEditor.js
js/components/PolygonSymbolizerEditor.js
js/components/RuleEditor.js
js/components/StrokeEditor.js
js/components/StyleModal.js
package.json

SDK-305
UI/UX as developed by @jjmulenex

New UI/UX for StyleModal

---

js/components/Dialog.js
js/components/StyleModal.js

Inline dialog

---

js/components/Dialog.js
js/components/LayerListItem.js
js/components/StyleModal.js

Closes #390 
See #389 (partly fixed)

Dialog fixes

---

__tests__/services/MapConfigService.test.js
js/services/MapConfigService.js
js/services/WFSService.js

Make sure we can persist and load WFS layers

---

js/services/BCSService.js

cc @thirystheory 
I changed it a bit, I will also update the sdk-apps example soon
Is there a known issue with the last base map, I'm getting exceptions on that one.

Add a BCS Service

---

js/components/BaseMapModal.js
js/services/BaseMapConfigService.js

cc @thirystheory 
this makes it possible to restore the default base map layers again see also: https://github.com/boundlessgeo/sdk-apps/commit/d551ca410b3d654c10311fda9d621287bfa329be

Move base map layer creation into a service

---

js/components/NewRuleModal.js
js/components/StyleModal.js

Add back option to add new rule in style dialog

---

js/components/LayerList.js
js/services/MapConfigService.js

this came up in  https://github.com/GeoNode/geonode-client/issues/169

Handle different projections in map config

---

__tests__/components/Bookmarks.test.js
js/components/Bookmarks.js
package.json

Upgrade to ol 4.0.1

---

__tests__/components/FillEditor.test.js
__tests__/components/FilterEditor.test.js
__tests__/components/StrokeEditor.test.js
__tests__/services/FilterService.test.js
__tests__/services/SLDService.test.js
js/components/FillEditor.js
js/components/FilterEditor.js
js/components/PointSymbolizerEditor.js
js/components/PolygonSymbolizerEditor.js
js/components/RuleEditor.js
js/components/StrokeEditor.js
js/components/StyleModal.js
js/services/FilterService.js
js/services/SLDService.js

SDK-321
SDK-314
basically replicates what maputnik, except for the NOR (only AND and OR for now)

New filter editor

---

js/components/QGISLegend.js

This came up in http://gis.stackexchange.com/questions/230949/dynamic-legend-in-openlayers-3 and is an easy fix

Only show QGISLegend item if layer is visible

---

js/components/FilterEditor.js

let me know if there are more issues

fixed the filter line alignment

---

__tests__/stores/LayerStore.test.js

SDK-287
we won't know if this fixes it until we have run Travis a few times

Structure LayerStore tests differently

---

__tests__/components/Dialog.test.js
js/components/Dialog.js

Add tests for Dialog

---

__tests__/components/Measure.test.js
__tests__/components/QGISPrint.test.js
__tests__/components/Select.test.js
__tests__/components/WFST.test.js
js/components/Button.js
js/components/QGISPrint.js

This came up in https://github.com/GeoNode/geonode-client/issues/171

Disable print if we are in 3D mode

---

src/components/FeatureTable.js

Make table options more compact (SDK-350)

---

src/components/Geolocation.js

this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/208

Have an option to specify zoom level in geolocation

---

__tests__/components/MapPanel.test.js
src/components/MapPanel.js

this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/223

Also fit extent on view if useHistory is false

---

src/components/Bookmarks.js

this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/203

Fix Bookmarks component in menu mode

---

src/components/Select.js

this came up in: https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/242

Add a clear option to the Select component

---

package.json
src/components/LayerListItem.js

this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/222

Make sure saving files works everywhere

---

src/components/LayerSelector.js

Fix wrong value in layer selector

---

src/components/InfoPopup.js
src/components/Navigation.js

this came up in: https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/260#issuecomment-288337251

Have default toolId set for Navigation and InfoPopup

---

src/components/QueryBuilder.js
src/stores/FeatureStore.js

this came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/217

Fix QueryBuilder refine function

---

README.md
package.json

this came up in #432 cc @theduckylittle

Make node LTS dependency more prominent

---

src/components/LayerListItem.js

Remove leftover buttons, change them to MenuItem

---

__tests__/components/Chart.test.js
src/components/Chart.js

Simplify Chart component and improve UI/UX

---

src/components/AddLayerModal.scss
src/components/LayerList.scss
src/components/LayerListItem.js

Handful of tweeks to the left Nav
- Improved base layers  all on all off behavior
- Footer button overlap fixed
- Adding spacer fixed width icon to right buttons

Left nav hot fix

---

src/components/AddLayerModal.js

Make sure upload and create new layer can be selected

---

.gitignore
src/components/AddLayerModal.js
src/components/Dialog.js
src/components/Dialog.scss
src/components/FilterModal.js
src/components/LayerList.js
src/components/LayerListItem.js
src/components/NewRuleModal.js
src/components/StyleModal.js

Update the Dialog class to use a Drawer

---

src/components/FeatureTable.js
src/stores/FeatureStore.js

Fix WFS remote sorting

---

src/components/Button.js
src/components/ZoomToLatLon.js

Redo the UI/UX of ZoomToLatLon

---

docs/developers.md
docs/getting_started.md
docs/tutorial.md
docs/writing_components.md

Now that our packages are published under an npm org, this updated the docs

Update docs for packages under npm org

---

src/components/EditPopup.js
src/components/FeatureTable.js

Wfst updates

---

src/components/Playback.js

Minor fixes to playback

---

src/components/AddLayerModal.js
src/components/LayerList.js

SDK-438
closes #440 
needed for WAB

Implement showUpload and showNew in LayerList

---

src/components/Measure.js
src/components/Select.js

Fixed the remaining issues with the active state
SDK-418

Make sure we pass on secondary to IconButton

---

src/components/Button.js

Use FocusRipple for active state

---

__tests__/components/EditPopup.test.js
src/components/AddLayerModal.js
src/components/EditPopup.js

Allow editing on uploaded layers

---

src/components/DrawFeature.js
src/components/EditPopup.js

Implement secondary state in DrawFeature

---

src/components/Button.js
src/components/Chart.js
src/components/InfoPopup.js

z-Index was the issue and the FocusRipple overriding any existing children

Fix up missing closer icon (SDK-452)

---

src/components/LayerList.js

closes #485 
this came up during SDK-465

Only show add button if inlineDialogs is false

---

src/components/AddLayerModal.js

Specify supported file extensions in accept
If other file extension is chosen, fail early with an error message

Fixes for error handling in upload

---

package.json
src/components/FeatureTable.js

First columns in table should not resize

---

__tests__/components/FeatureTable.test.js
src/components/QueryBuilder.js

This came up in https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/347

Add clear option to query builder

---

src/components/FeatureTable.js

so that we don't need a vertical scrollbar

Set pageSize of table based on height

---

.gitignore
__tests__/components/FeatureTable.test.js
src/components/FeatureTable.js
src/components/FeatureTable.scss

fixed spacing around table
added a scss for FeatureTable.js

Updated filter position

---

__tests__/components/LayerList.test.js
changelog/upgrade-notes.md
src/components/LayerList.js
src/components/LayerListItem.js

Implement new WAB setting showContent on group layers
Implement isGroupExpanded on group layers
SDK-480

showContent and isGroupExpanded for group layers in LayerList

---

__tests__/components/EditPopup.test.js
src/components/EditPopup.js

Use stopEvent true on EditPopup

---

src/components/FilterHelp.js
src/components/FilterModal.js

this came up in: https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/360

Fix alignment of FilterHelp in FilterModal

---

src/components/FeatureTable.js

fixes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/361

Fix pageSize calculation (SDK-486)

---

src/components/EditPopup.js

This is a replacement for #497 which got reverted

Different way to allow scroll in EditPopup

---

__tests__/components/EditPopup.test.js
src/components/EditPopup.js

Issues were:
- geometryName not correct
- geometry type not correct
SDK-489
closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/367

Fix up WFS-T inserts

---

src/components/LayerList.js
src/components/LayerListItem.js

Fixing layer list groups and re-working some selected logic

Layerlist group

---

src/components/InfoPopup.js

closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/372

Do not autoPan if hover

---

src/components/DrawFeature.js

SDK-492
closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/369

Disable geometry types for which is there is no layer

---

src/components/Bookmarks.js

closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/389

Change bookmark button to icon

---

src/components/Select.js

closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/316
SDK-409

Make sure children of group layers can be selected

---

changelog/upgrade-notes.md
src/components/DrawFeature.js
src/components/EditPopup.js
src/components/FeatureTable.js

Add option on layer called disableEdit

---

src/components/FeatureTable.js

Row height etc. might depend on font etc.

Get table page size in a more dynamic way

---

src/components/EditPopup.js

SDK-545
fixes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/408

Fix issues with re-saving insert in EditPopup

---

src/components/LayerList.js

Adding in a minWidth to handle ie11

---

src/components/EditPopup.js

once feature is in state
SDK-551
closes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/407

Make sure we run the filter function to update the layers

---

package.json
src/services/SLDService.js
src/services/WFSService.js

changes were needed to jsonix so it's now forked and we're using the fork for now until it gets addressed

Make sure we are compatible with webpack2

---

__tests__/components/Geocoding.test.js
__tests__/components/GeocodingResults.test.js
src/actions/GeocodingActions.js
src/components/BoundlessSdk.js
src/components/Geocoding.js
src/components/Geocoding.scss
src/components/GeocodingResults.js
src/reducers/geocoding.js

Adding in modal close

---

__tests__/components/LayerListItem.test.js
changelog/upgrade-notes.md
package.json
src/components/InfoPopup.js
src/components/LayerListItem.js
src/services/WFSService.js

Support vector tiles layers

---

src/components/FeatureTable.js

Fixes https://github.com/boundlessgeo/qgis-webappbuilder-plugin/issues/415

Make sure set selected as filter works when filtered

---

examples/basic/app.js
src/components/map.js

1. The map component now checks to ensure that the
layers are removed if they are not found in the current state.
2. The basic demo now has a "Remove Layer" button
which removes the states layer from the map.

Fix for removing layers.

---

__tests__/components/map.test.js
src/components/map.js

This adds support for raster tilejson
SDK-592

Add support for raster tilejson

---

src/components/map.js

This does add support for the vector layers
but multiple layer per source is demonstrating a bug
which only renders the first layer.

Added support for 'vector' type layers.

---

examples/basic/app.jsx
examples/basic/basic.css
src/components/map.jsx

Adds support for layers with type = background.  Only supports background-color.

Implement background layers.

---

__tests__/components/map.test.jsx
examples/basic/app.jsx
src/components/map.jsx

1. Added logic to the map component to recognize
the 'ref' attribute.
2. Added a test to ensure coverage.

Added support for the layer 'ref' property.

---

__tests__/components/map.test.jsx
__tests__/reducers/map.test.js
examples/basic/app.jsx
src/components/map.jsx
src/components/map/popup.jsx

this solves part of the issue in #566. 
layer min/max zoom values can be set, converted to ol min/max res values, and then updated both on gl source and ol rendered layer.

configureLayers handles changes to min/max zoom vals

---

__tests__/reducers/map.test.js
src/actions/map.js
src/reducers/map.js

1. Added new updateMetadata action.
2. Added reducer code to handle the update action.

Added the ability to tweak the map's metadata.

---

examples/clustering/app.jsx

This label example would also work for other
layer types but is demo'd on the clustered
layers.

Added an example of labels on clusters

---

__tests__/actions/drawing.test.js
__tests__/actions/map.test.js
__tests__/components/map.test.jsx
__tests__/components/map/popup.test.jsx
__tests__/reducers/map.test.js
__tests__/source/cluster.test.js
package.json
src/components/map.jsx
src/reducers/map.js

Some of the code didn't have enough coverage, this PR addresses that

Improve test coverage

---

__tests__/components/map.test.jsx
examples/popups/app.jsx
src/components/map.jsx

This allows for asynch layer queries to be added to the map.

Converted the features query to a promise.

---

__tests__/components/map-drawing.test.jsx
__tests__/components/map.test.jsx
src/components/map.jsx

This was the only component with little coverage left

Increase map component coverage

---

__tests__/reducers/map.test.js

This includes a more fully thought out version
of the tests for re-ordering layers. It features four
layers and tests placing one in the middle, end, and beginning
of the layer list.

Additional placeLayer/orderLayer tests.

---

__tests__/components/map.test.jsx
examples/index.html
examples/wms/addwmslayer.jsx
examples/wms/app.jsx
examples/wms/index.html
examples/wms/layerlist.jsx
examples/wms/wmspopup.jsx
src/components/map.jsx

Add more complete WMS example

---

__tests__/components/map.test.jsx
examples/basic/app.jsx
examples/basic/index.html
src/components/map.jsx

Zoom slider prop added to map with some tests
Added zoomslider to basic example
Adding tests and fixing lint

Adding in a simple map prop from zoom slider

---

src/reducers/map.js

1. Changed !raster to =geojson
2. ensured the null/undefined tests are more clearly referring to
the data.

Made the checks for null data more sane.

---

LICENSE.md
src/action-types.js
src/actions/drawing.js
src/actions/map.js
src/actions/print.js
src/components/history.js
src/components/legend.jsx
src/components/map.jsx
src/components/map/popup.jsx
src/constants.js
src/reducers/drawing.js
src/reducers/map.js
src/reducers/print.js
src/source/cluster.js
src/util.js

This adds the copyright headers back and the LICENSE.md file

Add license headers

---

__tests__/components/map.test.jsx
src/components/map.jsx

Handle undefined center, zoom, bearing in map component

---

examples/index.html
webpack-dev-server.config.js

Layer List example, clean branch

Adding in layer list example

---

examples/popups/app.jsx
examples/popups/index.html
src/components/map/popup.jsx
src/stylesheet/_popup.scss

Auto scolling of content in the sdk-popup container

made changes to enable auto scrolling

---

examples/wms/app.css
examples/wms/index.html
examples/wms/wmspopup.jsx

I adjusted the look of the popups for this example. Its a good example of how flexible the popups can be.

updated the Look and feel of the pop examples.

---

.travis.yml

This updates our Travis config with the correct set of branches

Update branch list in Travis config

---

__tests__/components/map.test.jsx
src/components/map.jsx

SDK-632
This is now ready for review.

Handle mapbox:// urls for sprites and sources

---

__tests__/components/map-cluster.test.jsx
src/components/map.jsx

Make sure we pass on map projection to clustering logic

---

examples/drawing/measure-table.jsx
examples/layer-list/components/layerList.jsx

This came up during #615 which showed warnings / errors for these issues

Minor fixes to the examples

---

examples/geolocation/app.css
examples/geolocation/app.jsx
examples/geolocation/index.html
examples/geolocation/track-position.jsx
examples/index.html
webpack-dev-server.config.js

App demonstrating geolocation capabilities with changes requested from closed PR #601 
JIRA ticket SDK-575

Geolocation App - round 2

---

__tests__/components/map-context.test.jsx
src/components/map.jsx

Make sure we reload layers/sources if version is undefined

---

src/components/map.js

Found two bugs when loading geojson files from a context file.
1. The .json files were not being resolved relative to the baseUrl.
2. The layers would cause an error as they wouldn't have metadata
for their internal version.
This patches fixes both of those bugs.

Fixes for GeoJson bugs.

---

__tests__/components/map-cluster.test.js
__tests__/components/map-geojson-source.test.js
__tests__/components/map.test.js
__tests__/reducers/map.test.js
src/components/map.js

Bring test coverage back up

---

package.json

cc @jjmulenex let me know if this is what you needed or not

Add watch task for babel

---

__tests__/actions/map.test.js
__tests__/components/map-time.test.js
src/actions/map.js
src/components/map.js
src/constants.js

SDK-647 and part of SDK-650 (WMS part)

Time support

---

README.md
package.json

* Also added spaces to make the README more readable

open the examples page by default

---

examples/basic-wgs84/app.js
examples/basic/app.js
examples/mb-bright/app.js
examples/mb-bright/index.html
examples/upload-map/app.js
src/components/map.js
src/reducers/map.js

This PR updates the spelling to respect the Mapbox brand guidelines: https://www.mapbox.com/about/press/brand-guidelines/

change MapBox to Mapbox

---

__tests__/root/util.test.js
src/util.js

getMin and getMax functions have been previously replaced w/ ol getResolutionForZoom function

deleting getMin and Max util functions that are no longer used

---

examples/examples.css
src/stylesheet/sdk.scss
tasks/build-examples.js

Blocked the li's
Added colors to LI headers and backgrounds
With a little flexbox to boot

updated layout for examples.

---

package.json

Using my nice words...
Having my browser open a new tab everytime I tweaked the
webpack configuration was driving me batty.

Add npm serve

---

src/components/map.js
src/util.js

There was a bug with the "time" keys when metadata was
not defined.
@CarlyLanglois  -- this should fix the bug you were seeing this morning.

Added new 'getKey' function to handled undef'd keys.

---

config/examples/example.html

as discussed / reported in slack

Use relative url for example index page

---

src/components/map.js

Change default wrapX to true

---

__tests__/components/map-geojson-source.test.js
__tests__/components/map.test.js
examples/realtime/app.js
examples/realtime/index.html
package.json
src/components/map.js
tasks/config.js

SDK-674
thanks to Mapbox for the inspiration https://www.mapbox.com/mapbox-gl-js/example/live-geojson/

Add realtime data example

---

config/templates/partials/header.html

Add back docs link

---

config/templates/index.html
config/templates/partials/header.html
examples/examples.css
examples/index.html

added get started button

---

examples/index.html

skipExamplePage is not used anymore

---

tasks/build-examples.js

This has been bothering me for a while ;)

Sort examples in index alphabetically

---

__tests__/actions/mapbox.test.js
__tests__/components/__snapshots__/legend.test.js.snap
__tests__/components/legend.test.js
__tests__/components/map-geojson-source.test.js
__tests__/components/map.test.js
__tests__/reducers/mapbox.test.js
examples/mb-bright/app.js
examples/mb-bright/index.html
examples/paint-change/app.js
examples/realtime/app.js
src/action-types.js
src/actions/mapbox.js
src/components/legend.js
src/components/map.js
src/reducers/mapbox.js

Vector legend

---

examples/wfst/app.js
tasks/config.js

Configure WFS-T example for the demo geoserver

---

src/components/legend.js

Empty vector legends should use empty text

---

__tests__/components/map/__snapshots__/zoomslider.test.js.snap
src/components/map/zoom-slider.js
src/stylesheet/_zoomcontrol.scss
src/stylesheet/_zoomslider.scss
src/stylesheet/sdk.scss

Tested in Chrome and Firefox....
will test in MS Edge....
Colors and sizes are VARs. Documentation to come at a later date

Styled the Zoom slider and zoom controls.

---

__tests__/components/wfs.test.js
examples/wfst/app.js
src/components/wfs.js

SDK-720
Tested with read-only GeoServer WFS and network error (shutdown Tomcat).

Handle exceptions in WFS-T

---

__tests__/components/map.test.js
src/components/map.js
src/reducers/map.js

Make sure updateSource triggers map re-render

---

docs/conf.json
docs/proptype-plugin.js
package.json
src/components/history.js
src/components/legend.js
src/components/map.js
src/components/map/popup.js
src/components/wfs.js

SDK-702
Uses the following template in jsdoc: ```jsdoc/templates/default/tmpl/properties.tmpl```

Document our propTypes

---

src/components/layer-list.js

The layer list now accepts a class for rendering groups
as well as layers.

Added better support for groups in the layer list

---

examples/feature-table/table.js
src/reducers/map.js

- Cleaned up unused variables.
- Migrated "var = " to "let =" as appropriate.

Fix for some small lint errors.

---

__tests__/components/layer-list.test.js
__tests__/components/map/__snapshots__/zoomslider.test.js.snap
docs/proptype-plugin.js
src/components/layer-list-item.js
src/components/layer-list.js
src/components/map/zoom-control.js
src/components/map/zoom-slider.js

Add missing docs for some of our components

---

examples/bookmark/index.html
examples/filter/index.html
examples/mb-bright/index.html
examples/paint-change/index.html

SDK-764 as reported by @walker

Map div is already in base template

---

examples/layer-list/app.js

Fixing layer lit example to represent layer-list-item in a new file

---

__tests__/reducers/map.test.js
src/reducers/map.js

Fix updateSource check for geojson

---

docs/getting-started.md

Add a note to the getting started about canvas

---

__tests__/components/layer-list.test.js
examples/layer-list/app.js
package.json
src/components/layer-list-item.js
src/components/layer-list.js
src/reducers/map.js

Add drag and drop to layerlist

---

__tests__/actions/map.test.js

Add tests for addWmsSource, addWfsSource and addTmsSource

---

examples/paint-change/app.js

#747 broke the paint change example, this PR fixes it

Fix broken paint change example

---

__tests__/components/map.test.js
package.json
src/components/map.js

SDK-769
The labels are a bit crowded though, is that to be expected @ahocevar ? Is it because the labels are in multiple layers, or is the new collission detection supported for that use case as well?

Upgrade ol and ol-mapbox-style

---

config/templates/example.html
package.json
webpack-example.config.js

Produce source maps for our hosted examples

---

docs/getting-started.md
package.json
src/components/map.js
src/components/mapboxgl.js
src/stylesheet/sdk.scss
webpack-example.config.js

this moves ol-mapbox-style to be a peerDependency, so we can switch between renderers

Do not unconditionally include ol/mapbox css

---

.gitignore
README.md
examples/mb-bright/app.js
examples/realtime/app.js
package.json
webpack-dev-server.config.js
webpack-example.config.js

Use dotenv for Mapbox API key

---

__tests__/actions/map.test.js
examples/basic/app.js
examples/clustering/app.js
examples/drawing/app.js
examples/feature-table/app.js
examples/filter/app.js
examples/geolocation/app.js
examples/layer-list/app.js
examples/legends/app.js
examples/paint-change/app.js
examples/popups/app.js
examples/realtime/app.js
examples/rotating/app.js
examples/sprite-animation/app.js
examples/sprites/app.js
examples/wfst/app.js
examples/wms/app.js
src/actions/map.js

Make sure we attribute OSM

---

__tests__/components/map.test.js
examples/tms/app.js
examples/tms/index.html
src/components/map.js

Add scheme tms support for XYZ raster

---

__tests__/components/map-drawing.test.js
env-setup.js
package.json

Fix intermittent Travis failure

---

__mocks__/fetch-jsonp.js
__tests__/components/map.test.js
examples/esri/app.js
examples/esri/index.html
package.json
src/components/map.js
src/constants.js

This adds support for ArcGIS REST Identify so we can display popups on top of Esri services

Add support for ArcGIS REST Identify

---

__tests__/actions/esri.test.js
__tests__/actions/mapinfo.test.js
__tests__/components/map-geojson-source.test.js
__tests__/components/map.test.js
__tests__/components/mapboxgl.test.js
__tests__/reducers/esri.test.js
__tests__/reducers/mapinfo.test.js
examples/featureservice/app.js
examples/featureservice/index.html
package.json
src/action-types.js
src/actions/esri.js
src/actions/mapinfo.js
src/components/esri.js
src/components/history.js
src/components/map.js
src/components/mapboxgl.js
src/constants.js
src/reducers/esri.js
src/reducers/mapinfo.js

Add read support for Esri ArcGIS Rest Feature Services

---

__tests__/actions/mapinfo.test.js
__tests__/components/map.test.js
__tests__/components/map/__snapshots__/mouseposition.test.js.snap
__tests__/components/map/mouseposition.test.js
__tests__/components/mapboxgl.test.js
__tests__/reducers/mapinfo.test.js
examples/basic/app.js
examples/basic/index.html
src/action-types.js
src/actions/mapinfo.js
src/components/map.js
src/components/map/mouseposition.js
src/components/mapboxgl.js
src/reducers/mapinfo.js

Mouseposition control

---

__tests__/actions/mapinfo.test.js
__tests__/components/map-geojson-source.test.js
__tests__/components/map.test.js
__tests__/components/mapboxgl.test.js
__tests__/components/wfs.test.js
__tests__/reducers/mapinfo.test.js
src/action-types.js
src/actions/mapinfo.js
src/components/map.js
src/components/mapboxgl.js
src/reducers/mapinfo.js

Set the map bounds in WGS84 in the mapinfo reducer

Set map extent in mapinfo reducer

---

DEVELOPING.md

Dep was missing from the developing notes.

Added 'pkg-config' dependency

---

__tests__/components/map.test.js
src/components/map.js

Add support for mapbox protocol in TileJSON raster

---

src/components/map.js

This is a temporary fix for SDK-841 until we get openlayers 5.0 that fixes hit detection for decluttered layers

Add an option for declutter, and set it to false for now

---

__tests__/components/legend.test.js
src/components/legend.js

Add ability for separate stroke layer for vector legends

---

__tests__/components/map-drawing.test.js
changelog/upgrade-notes.md
examples/drawing/app.js
src/components/map.js

Better handle selection and deselection

---

__tests__/components/map/__snapshots__/zoomslider.test.js.snap
__tests__/reducers/map.test.js
changelog/upgrade-notes.md
examples/basic/app.js
examples/basic/index.html
src/components/map.js
src/components/map/zoom-slider.js
src/components/mapboxgl.js
src/constants.js

Implement minZoom and maxZoom

---

__tests__/components/legend.test.js
package.json
src/components/legend.js

Legend should be visible if layer is invisible

---

__tests__/components/map.test.js
src/components/map.js

Fix layer order issue

---

examples/filter/filter.js
package.json
src/components/layer-list.js
src/components/legend.js
src/components/map.js
src/components/map/scaleline.js
src/components/mapboxgl.js
src/reducers/map.js

This PR fixes the 6 possible bugs and vulnerabilities reported by SonarQube, and also 3 "code smells"

Fix issues reported by SonarQube

---

src/reducers/map.js

See https://github.com/boundlessgeo/sdk/pull/824

Checking if source exists before accessing it

---

docs/proptype-plugin.js
src/components/map-common.js
src/components/map.js
src/components/mapboxgl.js
src/reducers/esri.js
src/reducers/source.js
src/reducers/wfs.js

SDK-888
I still need to check it this doesn't break our jsdoc generation though.

Remove duplicate code

---

docs/proptype-plugin.js
src/components/history.js
src/components/map-common.js
src/components/map.js

Ignore props from docs that cannot be used

---

Jenkinsfile

Run SonarQube only on master

---

.eslintrc
__tests__/components/map.test.js
package.json
src/components/legend.js
src/components/map.js

Make sure all promises have catch

---

Jenkinsfile

CI change only, will eventually need a npm token that is not read-only

Add publish release section to Jenkins file

---

Jenkinsfile
README.md

Also add the PR integration, and have a dependency check in a separate stage

Move to new SonarQube instance

---

package.json
src/components/WMSLegend.js
src/services/MapConfigService.js

Proxy the legend graphic request if appropriate and add version to call

Set version in GetLegendGraphic request and use proxy

---

src/actions/map.js

Update the docs to say that no filter will remove everything

---

__tests__/components/map-drawing.test.js
__tests__/components/map/__snapshots__/zoomslider.test.js.snap
__tests__/reducers/drawing.test.js
src/actions/drawing.js
src/components/map.js
src/reducers/drawing.js

Allow startModify to specify a feature

---

__tests__/components/map-drawing.test.js
src/components/map.js

When modifying a certain feature, turn of selection

---

src/components/map.js

This came up in the castling app, where getfeatureinfo wasn't working

Allow setting fetch options in map component

---

src/components/map.js

Fix scope issue in tileloaderror listener

---

src/components/map.js

So that people can have full control over this setting.

Make stopEvent configurable

---

docs/getting-started.md
examples/esri/app.js

Use addOsmSource

---

examples/basic/app.css
examples/basic/app.js
examples/basic/index.html
examples/map-controls/app.js
examples/map-controls/index.html
examples/mapname/app.css
examples/mapname/app.js
examples/mapname/index.html
examples/minmaxzoom/app.js
examples/minmaxzoom/index.html
examples/rasteropacity/app.js
examples/rasteropacity/index.html
src/components/map.js

Refactor our examples

---

src/components/map/popup.js
src/stylesheet/_popup.scss

Do not depend on fontawesome for the closer icon

---

sdk-examples-build.groovy

Update header, address false fail on info

Add pipeline build for examples deployer

---

__tests__/components/map.test.js
src/components/map.js

Use zIndex on all layer types

---

docs/getting-started.md

Make sure we use the correct versions of sdk and ol-mapbox-style

---

__tests__/components/legend.test.js
__tests__/components/map.test.js
__tests__/components/mapboxgl.test.js
src/components/history.js
src/components/legend.js
src/components/map.js
src/components/mapboxgl.js

SDK-1018
Trying to tackle the async render related issues in SDK as discussed here: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Fix async render issues

---

src/components/map.js

1. Checks for an Authorization header in fetchOptions.
2. When present, uses an async loader to get the data
using fetch, convert it to a BLOB and then set the Tile's
image to that URL.

Added Support for Headers with Tile Fetches

---

examples/multimap/app.css
examples/multimap/app.js
examples/multimap/index.html

Add new example with more than 1 map

---

src/components/map.js

The previous Auth0 support PR only worked with Images
this version adds support to vector tiles.

Add support for fetch options to VectorTiles

---

__tests__/components/map.test.js
changelog/v2.4.3.md
package.json
src/components/map.js

In the WFS GetFeature call, the required service parameter is missing

Service is a required parameter

---

src/components/wfs.js

So we can send Authorization headers for instance

Add fetch options to WFS component

---

changelog/v2.4.5.md
package.json
src/components/async-img.js
src/components/legend.js

If legend images are protected by auth, we need to be able to use fetch with headers to get them
MBSE-71

Async image legend

---

changelog/v2.4.6.md
package.json
src/components/map.js

Use source-layer as the identifier if present

---

changelog/v2.4.7.md
package.json
src/components/wfs.js

Make sure we send the correct content-type

---

__tests__/actions/map.test.js
changelog/v2.5.0.md
package.json
src/actions/map.js

Allow specification of the vendor-specific param TILED

---

src/components/map.js

Do not double load data on refresh of geojson source

---

__tests__/components/legend.test.js
src/components/legend.js

fix for https://sentry.io/boundless-inc/mbse/issues/605839660/
w/ test

add condition for a layer without a source in legend context

---

package.json
src/services/MapConfigTransformService.js

Fix thumbnail generation for minus sign in url templates

---

__tests__/actions/map.test.js
__tests__/components/map.test.js
src/actions/map.js
src/components/map.js

Add maxzoom value to OSM source, fix minzoom/maxzoom handling

---

__mocks__/fetch-jsonp.js
changelog/upgrade-notes.md
changelog/v2.6.0.md
package.json
src/actions/map.js
src/sagas/context.js

Remove setContext action, add upgrade notes

---

examples/upload-map/app.js
src/sagas/context.js
webpack-common.js
webpack-example.config.js

Fix examples in IE11

---

__tests__/components/map.test.js
changelog/v2.6.1.md
package.json
src/components/map.js

Fixes for addWmsSource

---

docs/getting-started.md

This fixes the getting started guide

Make sure the getting started actually works

---

src/components/map.js
src/reducers/map.js

Similar to https://github.com/boundlessgeo/ol-mapbox-style/pull/94

Change mapbox-gl-style imports

---

changelog/v2.7.1.md
package.json

Updates the version and release notes.

Release v2.7.1

---

__tests__/components/wfs.test.js
src/components/wfs.js

refs https://github.com/boundlessgeo/castling/pull/561

Add callback for transaction start in WFS-T

---

package.json

Please tag and release to npm for the recent bug fixes

Release 1.1.2
